### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by CloudS3c** [AlterRSPS/Alter#38]
- [ ] clean up the repo since i fully pushed the files that should of not been pushed. And now everyone who makes changes to their servers its being pushed also.

- [ ] inspect on_item_on_obj

- [ ] make that the cache would be downloaded at install task or ask the user if he wants to use osrs cache or w.e

- [ ] crc match

- [ ] overlay destination
