### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by CloudS3c** [AlterRSPS/Alter#89]
- [x] Implement RSCM
- [x]  Rename all methods in KotlinPlugin.kt from snake_case to camelCase
- [x]  Correct NPCs spawning on their death tile
- [x]  Tournament Interface fix.
- [x]  Item Set Interface fix.
- [x]  Correct weapon category texts caused by component misconfiguration
- [x]  Selected Attack Styles not saved
- [x]  Equipment Interface
- [x]  World map interface
    - [ ]  Full Screen mode
- [x]  Implement new defence properties [Elemental weakness / Melee and Ranged Attack Types]
    - [ ]  Implement their functionality
- [ ]  Before npc dies it's last hit gets rendered and looks weird need to verify if it's same but if i am not mistaking should be that all hits get removed when Npc dies.
- [x]  Decrypt map in Cache during `:Install` and `:decryptMap`
- [x]  Item stats load from Cache
- [x]  Override items from `data/cfg/itemOverriders`
- [x]  Thanks to [@Z-Kris](https://github.com/Z-Kris) most items contain proper Render Animations.
- [ ]  Item Equip Level Requirements
- [x]  Head class for PlayerInfo / NpcInfo
    - [ ]  Should change how we send it. So that properties would be updated and all of them would be sent. Currently we send them one by one.
- [x]  Fix ItemContainer test others were unable to run install without `-x test`
- [x]  Add link to correct xteas at README.MD
- [x]  Empty area clipping
- [x]  Run logic same as in OSRS
    - [ ]  Drain run energy math
- [x]  Shops not displaying items
- [x]  Handle connection reset.
- [x]  Add gradle wrapper
- [x]  Use Polars entity examine format.
- [x]  Chat box child fullscreen correction.
- [x]  Npc combat def specify which Plugin caused the exception
- [x]  Same name `x.plugin.kts` one of them wont get executed.
- [x]  Upgrade from Kotlin 1.7 to 2.0
- [ ]  Add Json Schemas for Game / Item Configs and other Data Files.
- [ ]  Re-write how commands get executed
- [ ]  Rewrite Skilling Plugins that were using Ints for entities to use RSCM
- [ ] Equip Unequip Sounds
- [ ] Xp drop interface as well as main game child is busted
- [ ] Items kept on death interface busted
- [ ] Region Music
	- [ ] Unlock music tracks https://oldschool.runescape.wiki/w/Map:Music_tracks
- [ ] When Npc dies , combat does not stop, Pawn still tries to hit and gets splashed '0'

## Path Finder
- [x]  Scrap out the older path finder.
- [x]  Implement [RsModV2 routeFinder](https://github.com/rsmod/rsmod/tree/main/engine/routefinder)
- [ ]  Move next to a Npc that is larger than 1x1 tile <-- Currently that is busted
- [x]  Property for Npc to use Smart or Dumb path finding
- [ ]  Larger npc pathing is not as on OSRS might also crash.
- [ ]  Ranged attacks moves next to npc should attack if within range.
- [ ] Ground Item options Pathing

## Bank interface:
- [ ]  Wrong varbit incrimination when depositing all to a tab.
- [ ]  When depositing all items, Attack Style is not reassigned
- [x]  Swap tabs
- [ ]  Bank inventory interface is set on wrong child on Fixed mode

**Comment by CloudS3c** [comment]
- Still using old skill interface = Need to implement Advance Settings <-- There is a option to switch between new and old Skill guide interface, i added the varbit that depends on that option, and will enable the new style by default.

**Comment by CloudS3c** [comment]
- [x] Npc does not get removed when it's dead + exception about transforming it to -1, had to use setInaccessible(), just need to find out why it removes the npc so fast, without letting it do death animation.

**Comment by MatthewBishop** [comment]
pushed fixes for the xteas not getting loaded in and also reimplemented projectiles. Checked them off.

**Comment by CloudS3c** [comment]
![image](https://github.com/AlterRSPS/Alter/assets/50030246/2d1cc138-288b-4c68-87f8-103bf91c83e2)

**Comment by CloudS3c** [comment]
![image](https://github.com/AlterRSPS/Alter/assets/50030246/a60cca19-116b-4261-89c0-e1825a80fefc)
![image](https://github.com/AlterRSPS/Alter/assets/50030246/af6d26cf-7e28-4e92-a30b-42af0cb0b125)
For some reason when you activate these, it will give Null Pointer due to `player.getInteractingSlot()` Which is bit weird as it shouldnt be doing that

**Comment by CloudS3c** [comment]
![image](https://github.com/AlterRSPS/Alter/assets/50030246/67611b4e-d4cb-4cd0-bcd7-006c83e2f4ff)
We are not assigning Render Animations yet by items, need to create open class for BlockInfo and make it reusable between Npc/Player classes

**Comment by CloudS3c** [comment]
![image](https://github.com/user-attachments/assets/c0f2bba0-1fa1-4ef9-be0b-2f1e6353e1fa)
